version: '3.8'
services:
  mongodb_container:
    container_name: mongodb
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: abc123
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: