version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'abc123'
      MYSQL_ROOT_PASSWORD: 'abc123'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data: